<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net462;net6.0-windows</TargetFrameworks>
		<AssemblyName>Gma.System.MouseKeyHook</AssemblyName>
		<RootNamespace>Gma.System.MouseKeyHook</RootNamespace>
		<LangVersion>10.0</LangVersion>
		<Nullable>enable</Nullable>
		<VersionPrefix>6.0.0</VersionPrefix>
		<GenerateAssemblyInfo>False</GenerateAssemblyInfo>
		<Deterministic>False</Deterministic>
		<UseWindowsForms>True</UseWindowsForms>
	</PropertyGroup>

	<PropertyGroup>
		<Authors>George Mamaladze; Victor Nova</Authors>
		<Description>
			This library attaches to windows global hooks, tracks keyboard and mouse clicks and movement and raises common .NET events with KeyEventArgs and MouseEventArgs, so you can easily retrieve any information you need:

			* Mouse coordinates
			* Mouse buttons clicked
			* Mouse wheel scrolls
			* Key presses and releases
			* Special key states

			Additionally, there is a possibility to supress certain keyboard or mouse clicks, or detect special key combinations.
		</Description>
		<PackageTags>keyboard;mouse;hook;event;global;spy</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="System.Windows.Forms">
			<Name>System.Windows.Forms</Name>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>